# Config file for automatic testing at https://travis-ci.org/sashw/latex-letter-gui/

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
  - pip install -r requirements.txt

before_install:
  - pip install codecov

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage --cover-package letter

after_success: codecov
