# Config file for automatic testing at https://travis-ci.org/sashw/latex-letter-gui/

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

addons:
  apt:
    packages:
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-recommended
    - texlive-lang-german
    - python3-pyqt5

before_install:
  - pip install codecov
  - pip install coveralls

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script: nosetests --with-coverage

after_success:
  - codecov
  - coveralls
