# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'letter.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 880)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 880))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.attachment_listing_box = QtWidgets.QGroupBox(self.centralwidget)
        self.attachment_listing_box.setGeometry(QtCore.QRect(310, 670, 191, 111))
        self.attachment_listing_box.setObjectName("attachment_listing_box")
        self.attachment_dot_radio = QtWidgets.QRadioButton(self.attachment_listing_box)
        self.attachment_dot_radio.setEnabled(True)
        self.attachment_dot_radio.setGeometry(QtCore.QRect(0, 30, 111, 26))
        self.attachment_dot_radio.setChecked(False)
        self.attachment_dot_radio.setObjectName("attachment_dot_radio")
        self.attachment_dash_radio = QtWidgets.QRadioButton(self.attachment_listing_box)
        self.attachment_dash_radio.setGeometry(QtCore.QRect(0, 60, 111, 26))
        self.attachment_dash_radio.setChecked(True)
        self.attachment_dash_radio.setObjectName("attachment_dash_radio")
        self.date_form_box = QtWidgets.QGroupBox(self.centralwidget)
        self.date_form_box.setGeometry(QtCore.QRect(890, 580, 111, 91))
        self.date_form_box.setObjectName("date_form_box")
        self.place_date_radio = QtWidgets.QRadioButton(self.date_form_box)
        self.place_date_radio.setGeometry(QtCore.QRect(0, 30, 111, 26))
        self.place_date_radio.setObjectName("place_date_radio")
        self.only_date_radio = QtWidgets.QRadioButton(self.date_form_box)
        self.only_date_radio.setGeometry(QtCore.QRect(0, 60, 111, 26))
        self.only_date_radio.setChecked(True)
        self.only_date_radio.setObjectName("only_date_radio")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(530, 660, 255, 141))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.markers_boxes_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.markers_boxes_layout.setObjectName("markers_boxes_layout")
        self.faltmarken_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.faltmarken_checkbox.setEnabled(True)
        self.faltmarken_checkbox.setAutoFillBackground(False)
        self.faltmarken_checkbox.setChecked(True)
        self.faltmarken_checkbox.setObjectName("faltmarken_checkbox")
        self.markers_boxes_layout.addWidget(self.faltmarken_checkbox)
        self.fenstermarken_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.fenstermarken_checkbox.setChecked(True)
        self.fenstermarken_checkbox.setObjectName("fenstermarken_checkbox")
        self.markers_boxes_layout.addWidget(self.fenstermarken_checkbox)
        self.lochermarke_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.lochermarke_checkbox.setChecked(True)
        self.lochermarke_checkbox.setObjectName("lochermarke_checkbox")
        self.markers_boxes_layout.addWidget(self.lochermarke_checkbox)
        self.trennlinien_checkbox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.trennlinien_checkbox.setChecked(True)
        self.trennlinien_checkbox.setObjectName("trennlinien_checkbox")
        self.markers_boxes_layout.addWidget(self.trennlinien_checkbox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(60, 40, 321, 211))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.recipient_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.recipient_layout.setObjectName("recipient_layout")
        self.recipient_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.recipient_label.setObjectName("recipient_label")
        self.recipient_layout.addWidget(self.recipient_label)
        self.recipient_text = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.recipient_text.setObjectName("recipient_text")
        self.recipient_layout.addWidget(self.recipient_text)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(820, 750, 251, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.buttons_layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.buttons_layout.setObjectName("buttons_layout")
        self.create_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.create_button.setObjectName("create_button")
        self.buttons_layout.addWidget(self.create_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttons_layout.addItem(spacerItem)
        self.save_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.save_button.setObjectName("save_button")
        self.buttons_layout.addWidget(self.save_button)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(620, 10, 441, 251))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.sender_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.sender_layout.setObjectName("sender_layout")
        self.sender_info_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.sender_info_label.setObjectName("sender_info_label")
        self.sender_layout.addWidget(self.sender_info_label)
        self.sender_fields_layout = QtWidgets.QHBoxLayout()
        self.sender_fields_layout.setObjectName("sender_fields_layout")
        self.sender_labels_layout = QtWidgets.QVBoxLayout()
        self.sender_labels_layout.setObjectName("sender_labels_layout")
        self.name_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.name_label.setObjectName("name_label")
        self.sender_labels_layout.addWidget(self.name_label)
        self.street_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.street_label.setObjectName("street_label")
        self.sender_labels_layout.addWidget(self.street_label)
        self.city_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.city_label.setObjectName("city_label")
        self.sender_labels_layout.addWidget(self.city_label)
        self.country_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.country_label.setObjectName("country_label")
        self.sender_labels_layout.addWidget(self.country_label)
        self.phone_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.phone_label.setObjectName("phone_label")
        self.sender_labels_layout.addWidget(self.phone_label)
        self.email_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.email_label.setObjectName("email_label")
        self.sender_labels_layout.addWidget(self.email_label)
        self.sender_fields_layout.addLayout(self.sender_labels_layout)
        self.sender_lines_layout = QtWidgets.QVBoxLayout()
        self.sender_lines_layout.setObjectName("sender_lines_layout")
        self.name_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.name_line.setObjectName("name_line")
        self.sender_lines_layout.addWidget(self.name_line)
        self.street_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.street_line.setObjectName("street_line")
        self.sender_lines_layout.addWidget(self.street_line)
        self.city_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.city_line.setObjectName("city_line")
        self.sender_lines_layout.addWidget(self.city_line)
        self.country_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.country_line.setObjectName("country_line")
        self.sender_lines_layout.addWidget(self.country_line)
        self.phone_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.phone_line.setObjectName("phone_line")
        self.sender_lines_layout.addWidget(self.phone_line)
        self.email_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.email_line.setObjectName("email_line")
        self.sender_lines_layout.addWidget(self.email_line)
        self.sender_fields_layout.addLayout(self.sender_lines_layout)
        self.sender_layout.addLayout(self.sender_fields_layout)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(800, 290, 258, 264))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.calendar_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.calendar_layout.setObjectName("calendar_layout")
        self.date_label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.date_label.setObjectName("date_label")
        self.calendar_layout.addWidget(self.date_label)
        self.calendarWidget = QtWidgets.QCalendarWidget(self.verticalLayoutWidget_5)
        self.calendarWidget.setMinimumDate(QtCore.QDate(2015, 8, 20))
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setObjectName("calendarWidget")
        self.calendar_layout.addWidget(self.calendarWidget)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(20, 640, 271, 181))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.attachment_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.attachment_layout.setObjectName("attachment_layout")
        self.attachment_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.attachment_label.setObjectName("attachment_label")
        self.attachment_layout.addWidget(self.attachment_label)
        self.attachment_text = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_6)
        self.attachment_text.setObjectName("attachment_text")
        self.attachment_layout.addWidget(self.attachment_text)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(20, 270, 761, 361))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.letter_content_layout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.letter_content_layout.setObjectName("letter_content_layout")
        self.subject_layout = QtWidgets.QHBoxLayout()
        self.subject_layout.setObjectName("subject_layout")
        self.subject_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.subject_label.setObjectName("subject_label")
        self.subject_layout.addWidget(self.subject_label)
        self.subject_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.subject_line.setObjectName("subject_line")
        self.subject_layout.addWidget(self.subject_line)
        self.letter_content_layout.addLayout(self.subject_layout)
        self.salutation_layout = QtWidgets.QHBoxLayout()
        self.salutation_layout.setObjectName("salutation_layout")
        self.salutation_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.salutation_label.setObjectName("salutation_label")
        self.salutation_layout.addWidget(self.salutation_label)
        self.salutation_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.salutation_line.setObjectName("salutation_line")
        self.salutation_layout.addWidget(self.salutation_line)
        spacerItem1 = QtWidgets.QSpacerItem(78, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.salutation_layout.addItem(spacerItem1)
        self.letter_content_layout.addLayout(self.salutation_layout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.content_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.content_label.setObjectName("content_label")
        self.verticalLayout.addWidget(self.content_label)
        self.content_text = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_7)
        self.content_text.setObjectName("content_text")
        self.verticalLayout.addWidget(self.content_text)
        self.greeting_layout = QtWidgets.QHBoxLayout()
        self.greeting_layout.setObjectName("greeting_layout")
        self.greeting_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.greeting_label.setObjectName("greeting_label")
        self.greeting_layout.addWidget(self.greeting_label)
        self.greeting_line = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.greeting_line.setObjectName("greeting_line")
        self.greeting_layout.addWidget(self.greeting_line)
        spacerItem2 = QtWidgets.QSpacerItem(78, 28, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.greeting_layout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.greeting_layout)
        self.letter_content_layout.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 26))
        self.menubar.setObjectName("menubar")
        self.menuEinstellungen = QtWidgets.QMenu(self.menubar)
        self.menuEinstellungen.setObjectName("menuEinstellungen")
        self.menuWeitere_Angaben = QtWidgets.QMenu(self.menuEinstellungen)
        self.menuWeitere_Angaben.setObjectName("menuWeitere_Angaben")
        self.menuMarkierungen = QtWidgets.QMenu(self.menuEinstellungen)
        self.menuMarkierungen.setObjectName("menuMarkierungen")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBankverbindung = QtWidgets.QAction(MainWindow)
        self.actionBankverbindung.setObjectName("actionBankverbindung")
        self.actionFaltmarken = QtWidgets.QAction(MainWindow)
        self.actionFaltmarken.setCheckable(True)
        self.actionFaltmarken.setChecked(True)
        self.actionFaltmarken.setObjectName("actionFaltmarken")
        self.actionFenstermarken = QtWidgets.QAction(MainWindow)
        self.actionFenstermarken.setCheckable(True)
        self.actionFenstermarken.setChecked(True)
        self.actionFenstermarken.setObjectName("actionFenstermarken")
        self.actionLochermarke = QtWidgets.QAction(MainWindow)
        self.actionLochermarke.setCheckable(True)
        self.actionLochermarke.setChecked(True)
        self.actionLochermarke.setObjectName("actionLochermarke")
        self.actionTrennlinien = QtWidgets.QAction(MainWindow)
        self.actionTrennlinien.setCheckable(True)
        self.actionTrennlinien.setChecked(True)
        self.actionTrennlinien.setObjectName("actionTrennlinien")
        self.actionAnhang = QtWidgets.QAction(MainWindow)
        self.actionAnhang.setObjectName("actionAnhang")
        self.menuWeitere_Angaben.addAction(self.actionBankverbindung)
        self.menuMarkierungen.addAction(self.actionFaltmarken)
        self.menuMarkierungen.addAction(self.actionFenstermarken)
        self.menuMarkierungen.addAction(self.actionLochermarke)
        self.menuMarkierungen.addAction(self.actionTrennlinien)
        self.menuEinstellungen.addAction(self.actionAnhang)
        self.menuEinstellungen.addAction(self.menuMarkierungen.menuAction())
        self.menuEinstellungen.addAction(self.menuWeitere_Angaben.menuAction())
        self.menubar.addAction(self.menuEinstellungen.menuAction())
        self.recipient_label.setBuddy(self.recipient_text)
        self.name_label.setBuddy(self.name_line)
        self.street_label.setBuddy(self.street_line)
        self.city_label.setBuddy(self.city_line)
        self.country_label.setBuddy(self.country_line)
        self.phone_label.setBuddy(self.phone_line)
        self.email_label.setBuddy(self.email_line)
        self.date_label.setBuddy(self.calendarWidget)
        self.attachment_label.setBuddy(self.attachment_text)
        self.subject_label.setBuddy(self.subject_line)
        self.salutation_label.setBuddy(self.salutation_line)
        self.content_label.setBuddy(self.content_text)
        self.greeting_label.setBuddy(self.greeting_line)

        self.retranslateUi(MainWindow)
        self.save_button.clicked.connect(MainWindow.save_tex)
        self.create_button.clicked.connect(MainWindow.create_pdf)
        self.actionFaltmarken.triggered['bool'].connect(self.faltmarken_checkbox.toggle)
        self.actionFenstermarken.triggered['bool'].connect(self.fenstermarken_checkbox.toggle)
        self.actionLochermarke.triggered['bool'].connect(self.lochermarke_checkbox.toggle)
        self.actionTrennlinien.triggered['bool'].connect(self.trennlinien_checkbox.toggle)
        self.faltmarken_checkbox.clicked['bool'].connect(self.actionFaltmarken.toggle)
        self.fenstermarken_checkbox.clicked['bool'].connect(self.actionFenstermarken.toggle)
        self.lochermarke_checkbox.clicked['bool'].connect(self.actionLochermarke.toggle)
        self.trennlinien_checkbox.clicked['bool'].connect(self.actionTrennlinien.toggle)
        self.create_button.clicked['bool'].connect(self.statusbar.clearMessage)
        self.save_button.clicked['bool'].connect(self.statusbar.clearMessage)
        self.actionBankverbindung.triggered['bool'].connect(MainWindow.showBank)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.name_line, self.street_line)
        MainWindow.setTabOrder(self.street_line, self.city_line)
        MainWindow.setTabOrder(self.city_line, self.country_line)
        MainWindow.setTabOrder(self.country_line, self.phone_line)
        MainWindow.setTabOrder(self.phone_line, self.email_line)
        MainWindow.setTabOrder(self.email_line, self.recipient_text)
        MainWindow.setTabOrder(self.recipient_text, self.subject_line)
        MainWindow.setTabOrder(self.subject_line, self.salutation_line)
        MainWindow.setTabOrder(self.salutation_line, self.content_text)
        MainWindow.setTabOrder(self.content_text, self.greeting_line)
        MainWindow.setTabOrder(self.greeting_line, self.calendarWidget)
        MainWindow.setTabOrder(self.calendarWidget, self.attachment_text)
        MainWindow.setTabOrder(self.attachment_text, self.place_date_radio)
        MainWindow.setTabOrder(self.place_date_radio, self.only_date_radio)
        MainWindow.setTabOrder(self.only_date_radio, self.attachment_dot_radio)
        MainWindow.setTabOrder(self.attachment_dot_radio, self.attachment_dash_radio)
        MainWindow.setTabOrder(self.attachment_dash_radio, self.faltmarken_checkbox)
        MainWindow.setTabOrder(self.faltmarken_checkbox, self.fenstermarken_checkbox)
        MainWindow.setTabOrder(self.fenstermarken_checkbox, self.lochermarke_checkbox)
        MainWindow.setTabOrder(self.lochermarke_checkbox, self.trennlinien_checkbox)
        MainWindow.setTabOrder(self.trennlinien_checkbox, self.create_button)
        MainWindow.setTabOrder(self.create_button, self.save_button)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.attachment_listing_box.setTitle(_translate("MainWindow", "Auflistungszeichen Anhang"))
        self.attachment_dot_radio.setText(_translate("MainWindow", "Strich"))
        self.attachment_dash_radio.setText(_translate("MainWindow", "Punkt"))
        self.date_form_box.setTitle(_translate("MainWindow", "Anzeige Datum"))
        self.place_date_radio.setText(_translate("MainWindow", "Ort, Datum"))
        self.only_date_radio.setText(_translate("MainWindow", "nur Datum"))
        self.faltmarken_checkbox.setText(_translate("MainWindow", "Faltmarken"))
        self.fenstermarken_checkbox.setText(_translate("MainWindow", "Fenstermarken"))
        self.lochermarke_checkbox.setText(_translate("MainWindow", "Lochermarke"))
        self.trennlinien_checkbox.setText(_translate("MainWindow", "Trennlinien Briefkopf und Fußzeile"))
        self.recipient_label.setText(_translate("MainWindow", "Adresse Empfänger"))
        self.create_button.setText(_translate("MainWindow", "PDF erstellen"))
        self.save_button.setText(_translate("MainWindow", "Tex speichern"))
        self.sender_info_label.setText(_translate("MainWindow", "Informationen Absender"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.street_label.setText(_translate("MainWindow", "Straße"))
        self.city_label.setText(_translate("MainWindow", "PLZ Ort"))
        self.country_label.setText(_translate("MainWindow", "Staat"))
        self.phone_label.setText(_translate("MainWindow", "Telefon"))
        self.email_label.setText(_translate("MainWindow", "E-Mail"))
        self.date_label.setText(_translate("MainWindow", "Datum"))
        self.attachment_label.setText(_translate("MainWindow", "Anhang"))
        self.subject_label.setText(_translate("MainWindow", "Betreff"))
        self.salutation_label.setText(_translate("MainWindow", "Anrede"))
        self.content_label.setText(_translate("MainWindow", "Brieftext"))
        self.greeting_label.setText(_translate("MainWindow", "Grußformel"))
        self.menuEinstellungen.setTitle(_translate("MainWindow", "Einstellungen"))
        self.menuWeitere_Angaben.setTitle(_translate("MainWindow", "weitere Angaben ändern"))
        self.menuMarkierungen.setTitle(_translate("MainWindow", "Markierungen"))
        self.actionBankverbindung.setText(_translate("MainWindow", "Bankverbindung"))
        self.actionFaltmarken.setText(_translate("MainWindow", "Faltmarken"))
        self.actionFenstermarken.setText(_translate("MainWindow", "Fenstermarken"))
        self.actionLochermarke.setText(_translate("MainWindow", "Lochermarke"))
        self.actionTrennlinien.setText(_translate("MainWindow", "Trennlinien Briefkopf und Fußzeile"))
        self.actionAnhang.setText(_translate("MainWindow", "Anhang"))

